In [73]:
from bs4 import BeautifulSoup
import re
import requests
import time
import pandas as pd

In [74]:
fish_list.index('sea squirt')

78

In [75]:
fish_list = ['alewife',
   'Alewife_(fish)',
 'american eel',
 'american shad',
 'amphipod',
 'sea anemone',
 'asian shore crab',
   'Hemigrapsus_sanguineus',
 'atlantic herring',
 'atlantic menhaden',
 'atlantic needlefish',
 'atlantic silverside',
 'atlantic tomcod',
             
 'bay anchovy',
 'black fingered mud crab',
 'black sea bass',
 'blue crab',
   'Callinectes_sapidus',
 'blue mussel',
 'blueback herring',
 'bluefish',
 'bluespotted cornetfish',
 'box crab',
 'colonial tunicate',
    'tunicate',
 'comb jelly beroe',
    'Beroe_cucumis',
 'comb jelly leidyi',
             'Mnemiopsis',
 'common periwinkle snail',
             'Common_periwinkle',
 'cunner',
 'eastern mud snail',
             
             
 'eastern oyster',
 'golden star tunicate',
 'green crab',
 'grubby',
             'Myoxocephalus_aenaeus',
 'hogchoker',
 'horseshoe crab',
 'hydromedusa',
 'hydrozoa',
 'isopod',
 'lady crab',
 'lions mane jellyfish',
 'long clawed hermit crab',
             'Pagurus_longicarpus',
 'mantis shrimp',
 'mole crab',
 'moon jelly',
 'mud snail',
             'Nassariidae',
             
 'mullet fish',
             'Mullet_(fish)',
 'naked goby',
             'Gobiosoma_bosc',
 'needlefish',
 'northern kingfish',
             'Menticirrhus_saxatilis',
 'northern pipefish',
 'northern puffer',
 'northern sea robin',
 'northern seahorse',
 'northern stargazer',
 'oyster drill snail',
             'Urosalpinx_cinerea',
 'oyster toadfish',
 'pin fish',
 'pollock',
 'red beard sponge',
 'ribbed mussel',
             'Geukensia_demissa',
 'sand shrimp',
             'Crangon_septemspinosa',
 'sandworm',
             'Alitta_virens',
 'scud',
             'Amphipoda',
             
             
 'sea squirt',
 'seaboard goby',
             'Gobiosoma_ginsburgi',
 'sennet',
             'Barracuda',
 'sheepshead porgy',
 'shore shrimp',
             'Palaemonetes',
 'silver perch',
             'American_silver_perch',
 'skilletfish',
             'Gobiesox_strumosus',
 'softshell clam',
 'spider crab',
 'spot',
             'Spot_(fish)',
 'spotted hake',
 'spotted whiff',
             'Citharichthys', #can be more specific
 'striped anchovy',
             'Anchoa', # might be able to get more specific?
 'striped bass',
 'striped burrfish',
 'striped searobin',
 'summer flounder',
 'tautog',
 'tube worm',
 'tunicate',
 'undetermined jelly',
 'unidentified anchovy',
 'unidentified bass',
 'unidentified clam',
 'unidentified comb jelly',
 'unidentified fish',
 'unidentified flatfish',
 'unidentified flounder',
 'unidentified hermit crab',
 'unidentified herring',
 'unidentified jelly fish',
 'unidentified menhaden',
 'unidentified mud crab',
 'unidentified mussel',
 'unidentified polychaete worm',
 'unidentified porgy',
 'unidentified sculpin',
 'unidentified sea snail',
 'unidentified shrimp',
 'unidentified sponge',
 'western mosquito fish',
 'whelk snail',
 'white fingered mud crab',
 'white mullet',
 'white perch',
 'windowpane flounder',
 'winter flounder',
 'wrasel sea bass']

In [76]:
count = 0
taxon_list= []
for name in fish_list:
    count +=1
    if count < 78:
        continue
    try:
        fish =requests.get('https://en.wikipedia.org/wiki/' + name)
        time.sleep(2)
        fish_soup = BeautifulSoup(fish.text)
        info = fish_soup.find(class_ = 'biota').find_all('td')
        taxon_dict = {}
        for i,x in enumerate(info):
            cx =  x.get_text(strip=True)
            if cx in ['Kingdom:', 'Phylum:','Class:','Order:','Family:','Genus:','Species:']:
                taxon_dict[cx] = re.sub(r'\xa0','',info[i+1].get_text(strip=True))
        taxon_dict['Name'] = name
        taxon_list.append(taxon_dict)
        
        #info = fish_soup.find(class_ = 'biota').find_all('td')[3:17]
        #print(name)
        #taxon = [re.sub(r'\xa0','',x.get_text(strip=True)) for x in info]
        #print(taxon)
        #keys = [i for i in taxon if taxon.index(i)%2 ==0]
        #values = [i for i in taxon if taxon.index(i)%2 !=0]
        #taxon_dict = dict(zip(keys,values))
        #taxon_dict['Name'] = name
        #taxon_list.append(taxon_dict)
        
        
        
    except:
        print(name)
    if count > 98:
        break

seaboard goby
sennet
shore shrimp
silver perch
skilletfish
spot
spotted whiff
striped anchovy
tube worm
undetermined jelly

# Stopped on tube worm

In [77]:
df = pd.DataFrame(taxon_list)

In [78]:
df[['Kingdom:', 'Phylum:','Class:','Order:','Family:','Genus:','Species:', 'Name']]

,Kingdom:,Phylum:,Class:,Order:,Family:,Genus:,Species:,Name
0,Animalia,Arthropoda,Malacostraca,"AmphipodaLatreille, 1816[1]",NaN,NaN,NaN,Amphipoda
1,Animalia,Chordata,"AscidiaceaBlainville, 1824",NaN,NaN,NaN,NaN,sea squirt
2,Animalia,Chordata,Actinopterygii,Perciformes,Sparidae,Calamus,C.penna,sheepshead porgy
3,Animalia,Mollusca,Bivalvia,Myida,Myidae,Mya,M.arenaria,softshell clam
4,Animalia,Arthropoda,Malacostraca,Decapoda,NaN,NaN,NaN,spider crab
5,Animalia,Chordata,Actinopterygii,Gadiformes,Phycidae,Urophycis,U.regia,spotted hake
6,Animalia,Chordata,Actinopterygii,Perciformes,Moronidae,Morone,M.saxatilis,striped bass
7,Animalia,Chordata,Actinopterygii,Tetraodontiformes,Diodontidae,Chilomycterus,C.schoepfi,striped burrfish
8,Animalia,Chordata,Actinopterygii,Scorpaeniformes,Triglidae,Prionotus,P.evolans,striped searobin
9,Animalia,Chordata,Actinopterygii,Pleuronectiformes,Paralichthyidae,Paralichthys,P.dentatus,summer flounder
10,Animalia,Chordata,Actinopterygii,Labriformes,Labridae,"TautogaMitchill, 1814",T.onitis,tautog
11,Animalia,Chordata,NaN,NaN,NaN,NaN,NaN,tunicate