# Plan: Reformat to include Date, Time, Weathe & Air Temp, Water Temp, Tide Times, Tide is Moving, DO, PH, Salinity, Turbidity, # of Student Seiners, # of visitors, Instructors/ Seine Staff, Hauls, Common Name, Quantity,  # Brought to Ed Center, Other Info, Notes from seining season,

## Matching to the 2017 version. No other season has all of these columns.

In [133]:
import pandas as pd
import numpy as np
from datetime import datetime

In [134]:
def reformat_recent(df):
    init_list = df.columns.values[:14]
    curr_vals = df.loc[0][:14]
    for i, row in df.iterrows():
        if pd.isnull(df.loc[i,'Date']):
            df.loc[i] = list(curr_vals) + list(df.loc[i][14:])
        else:
            curr_vals = df.loc[i][:14]
    return df

In [135]:
def add_columns(curr_df, match_df):
    for col in match_df.columns.values:
        if col not in curr_df:
            curr_df[col] = ""
    return curr_df[match_df.columns.values]

In [136]:
csv_2008 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=737788186&format=csv'
csv_2009 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1188626592&format=csv'
csv_2010 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1492092969&format=csv'
csv_2011 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1154911519&format=csv'
csv_2012 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1815364461&format=csv'
csv_2013 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1417342758&format=csv'
csv_2014 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1605738199&format=csv'
csv_2015 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=0&format=csv'
csv_2016 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1068275557&format=csv'
csv_2017 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=126889157&format=csv'
csv_2018 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=375464720&format=csv'

In [137]:
combined_df = reformat_recent(pd.read_csv(csv_2017))

combined_df['Scientific Name'] = ''

In [138]:
#moving the scientific name column
combined_df =  combined_df[list(combined_df.columns.values[:14])+list(combined_df.columns.values[-1:]) + list(combined_df.columns.values[14:-1])]

In [139]:
df_2018 = pd.read_csv(csv_2018)
df_2018.rename(columns= {"NOTES FROM SEINE:":"NOTES FROM SEINEING SEASON:"})
df_2018 = add_columns(df_2018, combined_df)
df_2018 = reformat_recent(df_2018)
combined_df = pd.concat([combined_df, df_2018], axis = 0)

In [140]:
combined_df

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
0,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,Comb Jelly,TMTC,NaN,NaN,"During several seines throughtout the summer, ..."
1,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,Atlantic Menhaden,1,NaN,NaN,NaN
2,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,YOY Blueback Herring *,14,Peter took to lab,refer to season notes --->,NaN
3,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,YOY American Shad *,1,Peter took to lab,refer to season notes --->,NaN
4,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,YOY Striped Bass,1,1,NaN,NaN
5,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,Shore Shrimp,2,2,NaN,NaN
6,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,Mud Snail,3,2,NaN,NaN
7,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,Oyster Drill Snail,1,NaN,NaN,NaN
8,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,YOY Blue Crab,1,NaN,Male,NaN
9,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,Asian Shore Crabs,2,NaN,Pregnant females,NaN
10,6/3/2017 WORLD SCIENCE FESTIVAL,10:00 AM- 11:30 AM,"68 F @ 9:45 AM, Cloudy","59 F @ 9 AM, 62 F @ 10 AM","High Tide: 4:53 AM, Low Tide: 10:54 AM",OUT,9,did not perform,22 ppt (w/ hydrometer and refractometer),"20.4 cm, 40 NTU",NaN,118,"Peter Park, Haley, Shad, Isa, Christina, 2 BBP...",between 10-14 (two nets going at once),,Snail eggs,unknown,NaN,"On a blade of algae, possibly 15-20 eggs",NaN
11,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,YOY Blueback Herring *,38,NaN,NaN,NaN
12,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,Comb Jelly,20,NaN,NaN,NaN
13,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,Striped Bass,1,1,10 cm,"During several seines throughtout the summer, ..."
14,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,Bay Anchovy,1,NaN,6 cm,NaN
15,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,Pipefish,2,NaN,pregnant female 12 cm,NaN
16,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,Sand Shrimp,16,16,NaN,NaN
17,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,Asian Shore Crabs,1,NaN,NaN,NaN
18,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,Glass Shrimp (shore shrimp),1,1,NaN,NaN
19,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,Mud Snail,2,2,NaN,NaN
20,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,NaN,NaN,NaN,NaN,NaN
21,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,NaN,NaN,NaN,NaN,NaN
22,6/9/2017,3:30 PM- 5:00 PM,"90 F @ 3PM, 81 F @ 5 PM","66 F @ 3 PM, 63 F @ 5PM","High Tide: 9:44 PM, Low Tide: 3:23 PM",IN,"4, 0 (two tests by students)","7, 7 (two tests by students)","23, 22 ppt",Did not perform,8 (St. Francis After School) plus few from YES...,NaN,"Christina, Isa, Haley, Eliza",unknown,,NaN,NaN,NaN,NaN,NaN
23,6/10/17,9:30 AM- 11:30 PM,75 F,73 F,"High Tide: 5:55 AM, Low Tide: 11:45 AM",OUT,0,8,21 ppt,Did not perform,students too young,NaN,"Christina, Isa, Eliza, Haley, 4 SA, Laura",at least 10,,Blueback Herring *,5,NaN,NaN,NaN
24,6/10/17,9:30 AM- 11:30 PM,75 F,73 F,"High Tide: 5:55 AM, Low Tide: 11:45 AM",OUT,0,8,21 ppt,Did not perform,students too young,NaN,"Christina, Isa, Eliza, Haley, 4 SA, Laura",at least 10,,Pipefish,1,1,NaN,NaN
25,6/10/17,9:30 AM- 11:30 PM,75 F,73 F,"High Tide: 5:55 AM, Low Tide: 11:45 AM",OUT,0,8,21 ppt,Did not perform,students too young,NaN,"Christina, Isa, Eliza, Haley, 4 SA, Laura",at least 10,,Blue Crab,2,NaN,"1 small YOY with visible swimmers, 1 species u...",NaN
26,6/10/17,9:30 AM- 11:30 PM,75 F,73 F,"High Tide: 5:55 AM, Low Tide: 11:45 AM",OUT,0,8,21 ppt,Did not perform,students too young,NaN,"Christina, Isa, Eliza, Haley, 4 SA, Laura",at least 10,,Asian Shore Crab,3,NaN,NaN,"During several seines throughtout the summer, ..."
27,6/10/17,9:30 AM- 11:30 PM,75 F,73 F,"High Tide: 5:55 AM, Low Tide: 11:45 AM",OUT,0,8,21 ppt,Did not perform,students too young,NaN,"Christina, Isa, Eliza, Haley, 4 SA, Laura",at least 10,,Sand Shrimp,2,2,NaN,NaN
28,6/10/17,9:30 AM- 11:30 PM,75 F,73 F,"High Tide: 5:55 AM, Low Tide: 11:45 AM",OUT,0,8,21 ppt,Did not perform,students too young,NaN,"Christina, Isa, Eliza, Haley, 4 SA, Laura",at least 10,,Glass shrimp,7,7,NaN,NaN
29,6/10/17,9:30 AM- 11:30 PM,75 F,73 F,"High Tide: 5:55 AM, Low Tide: 11:45 AM",OUT,0,8,21 ppt,Did not perform,students too young,NaN,"Christina, Isa, Eliza, Haley, 4 SA, Laura",at least 10,,mud snail,6,6,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Periwinkle,1,1,NaN,
101,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Atlantic Menhaden,6,0,NaN,
102,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Comb Jelly,17,0,NaN,
103,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Blue Crab,6,2,largest ~ 3 inches,
104,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Tautog,3,3,NaN,
105,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Long Clawed Hermit Crab,18,18,NaN,
106,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Ribbed Mussel,1,1,NaN,
107,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Pipefish,2,0,2.5 in,
108,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silverside,12,4,NaN,
109,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Bay Anchovy,4,0,3 dead,
110,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silver Perch,4,1,NaN,
111,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Blue Crab,3,0,NaN,
112,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Hermit Crab,10,10,NaN,
113,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Moon Jelly,1,0,NaN,
114,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Comb Jelly,17,0,NaN,
115,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Mud Snail,6,0,1 dead,
116,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Skilletfish,1,1,NaN,
117,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,shore shrimp,6,6,NaN,
118,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Sand Shrimp,4,4,NaN,
119,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Bluefish,11,0,1 dead,
120,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Atlantic Silverside,5,0,1 dead,
121,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Porgy,1,0,NaN,
122,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Comb Jelly,70,0,NaN,
123,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Moon Jelly,2,0,NaN,
124,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Mud Snail,2,0,NaN,
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [141]:
df_2016 =  pd.read_csv(csv_2016)
df_2016.rename(columns={"Weather (exact air temp):": 'Weather & Air Temp:', "# student seiners (12+)": '# student seiners (CLASSES ONLY)',"# of visitors (Public Seine)":'# of visitors (Public Seine ONLY)'}, inplace=True)
df_2016 = add_columns(df_2016, combined_df)
df_2016 = reformat_recent(df_2016)
combined_df = pd.concat([df_2016,combined_df], axis=0)

In [142]:
combined_df

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
0,5/26/2016,4:30-5:30 PM,86 F,70 F,,,6,did not do,35 ppt,,"~ 18, St. Francis",NaN,Christina,~7,Ctenophora,Comb Jelly,11,11,died because of bubbler,
1,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,pipefish,1,NaN,~10 cm,
2,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,Altanic Silverside,4,4,eaten quickly by tank fish,
3,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,mud snail,1,1,~2 cm,
4,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,whelk snail,1,NaN,"~2 cm, may be different snail speices",
5,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,ghost shrimp,3,3,NaN,
6,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,Green crab,2,NaN,NaN,
7,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,Asian Shore Crab,~20,4,most females pregnant,
8,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,Mussels,~6,NaN,NaN,
9,5/31/2016,10:00 AM- 12:00PM,"75 F, breezy",70 F,,,4,7,35 ppt,,NaN,NaN,"Christina, Sigrun, Isa, Eliza, 1 volunteer, 3 ...",10,NaN,comb jelly,~50,11,NaN,
10,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,Silverside,2,NaN,NaN,
11,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,Atlantic Tomcod,1,NaN,NaN,
12,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,pipefish,1,1,NaN,
13,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,Asian Shore Crab,5,NaN,1 male (missing claw) 1 female (pregnant) 3 yo...,
14,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,YOY crab (Blue Crab),1,NaN,NaN,
15,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,Mussels,2,NaN,NaN,
16,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,comb jelly,25,NaN,NaN,
17,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,shrimp,1,NaN,NaN,
18,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,mud snail,2,NaN,1 dead,
19,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,oyster shell,1,NaN,dead,
20,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,Slipper Snail Shell,1,NaN,dead,
21,6/1/2016,10:00AM- 12:00PM,77 F,70 F,,,4,7,24 ppt,,NaN,NaN,"Christina, Eliza, Haley, Isa, BOP",?,NaN,Sandworm,1,NaN,~ 2 inches,
22,6/4/16,2:00PM- 3:30PM,73 F,79 F,,,4,7,22 ppt,,NaN,105,"Isa, Christina, Krista, Ethan, Ryan, Sara, Laura",Many,NaN,Silverside,72,20,5 were dead,
23,6/4/16,2:00PM- 3:30PM,73 F,79 F,,,4,7,22 ppt,,NaN,105,"Isa, Christina, Krista, Ethan, Ryan, Sara, Laura",Many,NaN,comb jelly,80,NaN,NaN,
24,6/4/16,2:00PM- 3:30PM,73 F,79 F,,,4,7,22 ppt,,NaN,105,"Isa, Christina, Krista, Ethan, Ryan, Sara, Laura",Many,NaN,Atlantic Tomcod,1,1,NaN,
25,6/4/16,2:00PM- 3:30PM,73 F,79 F,,,4,7,22 ppt,,NaN,105,"Isa, Christina, Krista, Ethan, Ryan, Sara, Laura",Many,NaN,Striped Bass,11,2,NaN,
26,6/4/16,2:00PM- 3:30PM,73 F,79 F,,,4,7,22 ppt,,NaN,105,"Isa, Christina, Krista, Ethan, Ryan, Sara, Laura",Many,NaN,Green crab,2,1,NaN,
27,6/4/16,2:00PM- 3:30PM,73 F,79 F,,,4,7,22 ppt,,NaN,105,"Isa, Christina, Krista, Ethan, Ryan, Sara, Laura",Many,NaN,Slipper Shell,5,NaN,one dead,
28,6/4/16,2:00PM- 3:30PM,73 F,79 F,,,4,7,22 ppt,,NaN,105,"Isa, Christina, Krista, Ethan, Ryan, Sara, Laura",Many,NaN,Asian Shore Crab,7,NaN,NaN,
29,6/4/16,2:00PM- 3:30PM,73 F,79 F,,,4,7,22 ppt,,NaN,105,"Isa, Christina, Krista, Ethan, Ryan, Sara, Laura",Many,NaN,Sandworm,1,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Periwinkle,1,1,NaN,
101,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Atlantic Menhaden,6,0,NaN,
102,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Comb Jelly,17,0,NaN,
103,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Blue Crab,6,2,largest ~ 3 inches,
104,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Tautog,3,3,NaN,
105,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Long Clawed Hermit Crab,18,18,NaN,
106,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Ribbed Mussel,1,1,NaN,
107,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Pipefish,2,0,2.5 in,
108,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silverside,12,4,NaN,
109,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Bay Anchovy,4,0,3 dead,
110,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silver Perch,4,1,NaN,
111,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Blue Crab,3,0,NaN,
112,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Hermit Crab,10,10,NaN,
113,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Moon Jelly,1,0,NaN,
114,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Comb Jelly,17,0,NaN,
115,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Mud Snail,6,0,1 dead,
116,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Skilletfish,1,1,NaN,
117,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,shore shrimp,6,6,NaN,
118,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Sand Shrimp,4,4,NaN,
119,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Bluefish,11,0,1 dead,
120,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Atlantic Silverside,5,0,1 dead,
121,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Porgy,1,0,NaN,
122,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Comb Jelly,70,0,NaN,
123,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Moon Jelly,2,0,NaN,
124,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Mud Snail,2,0,NaN,
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [143]:
df_2015 =  pd.read_csv(csv_2015)
df_2015.rename(columns={"Weather (exact air temp):": 'Weather & Air Temp:', "#of Participants":'# of visitors (Public Seine ONLY)', "Instructors/Staff:":"Instructors/ Seine Staff:", "Other info (Dead/Alive)":"Other info (Gender, Length, Dead/Alive, other physical description)"}, inplace=True)
df_2015 = add_columns(df_2015, combined_df)
df_2015 = reformat_recent(df_2015)
combined_df = pd.concat([df_2015,combined_df], axis=0)

In [144]:
combined_df

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
0,5/7/2015,?,?,?,,,?,?,?,,,?,?,,NaN,Glass Shrimp,5,,NaN,
1,5/7/2015,?,?,?,,,?,?,?,,,?,?,,NaN,Sand Worm,1,,NaN,
2,5/7/2015,?,?,?,,,?,?,?,,,?,?,,NaN,Asian shore crab,3,,NaN,
3,5/30/2015,11:35-12:45pm,77 F,68 F,,,4,7,22,,,50,"Eliza, Shellita, Kathy Gurland",,Morone Saxatilis,Striped Bass,1,,Alive,
4,5/30/2015,11:35-12:45pm,77 F,68 F,,,4,7,22,,,50,"Eliza, Shellita, Kathy Gurland",,Menidia Menidia,Atlantic Silverside,1,,Alive,
5,5/30/2015,11:35-12:45pm,77 F,68 F,,,4,7,22,,,50,"Eliza, Shellita, Kathy Gurland",,Unknown,Sea Snail,2,,Alive,
6,5/30/2015,11:35-12:45pm,77 F,68 F,,,4,7,22,,,50,"Eliza, Shellita, Kathy Gurland",,Palaemonetes,Ghost Shrimp,3,,Alive,
7,6/9/2015,12:25,78 F,Not Taken,,,do 5,pH 7,s 21,,,20 P,"Nim, Isa, Krista, Anita, Maria M, Maria GM",,Morone Saxatilis,Striped Bass,9,,Alive,
8,6/9/2015,12:25,78 F,Not Taken,,,do 5,pH 7,s 21,,,20 P,"Nim, Isa, Krista, Anita, Maria M, Maria GM",,Botryllus Schlosseri,Golden Star Colonial Tunicate,1,,Alive,
9,6/9/2015,12:25,78 F,Not Taken,,,do 5,pH 7,s 21,,,20 P,"Nim, Isa, Krista, Anita, Maria M, Maria GM",,Mytilus edulis,Blue Muscle,1,,Alive,
10,6/11/2015,11:10,79 F,Not Taken,,,4,pH 7,25,,,25 P,"Nim, Isa, Krista, Anita, Maria M, Darby",,Botryllus Schlosseri,colonial tunicate,1,,Alive,
11,6/11/2015,11:10,79 F,Not Taken,,,4,pH 7,25,,,25 P,"Nim, Isa, Krista, Anita, Maria M, Darby",,Morone Saxatilis,striped bass,8,,Alive,
12,6/11/2015,11:10,79 F,Not Taken,,,4,pH 7,25,,,25 P,"Nim, Isa, Krista, Anita, Maria M, Darby",,Hippocampus,pipe fish,1,,Alive,
13,6/11/2015,11:10,79 F,Not Taken,,,4,pH 7,25,,,25 P,"Nim, Isa, Krista, Anita, Maria M, Darby",,Calappa,box crab,1,,Alive,
14,6/11/2015,11:10,79 F,Not Taken,,,4,pH 7,25,,,25 P,"Nim, Isa, Krista, Anita, Maria M, Darby",,Hemagrapsis sanguineus,asian shore crab,6,,Alive,
15,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Hippocampus,pipe fish,1,,Alive,
16,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Pseudopleuronectes americanus,winter flounder,1,,Alive,
17,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Botryllus Schlosseri,colonial tunicate,10 to 15,,Alive,
18,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Paguroidea,hermit crab,4,,Alive,
19,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,NaN,snails,4,,Alive,
20,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Morone Saxatilis,striped bass,5,,Alive,
21,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Tautogolabrus adspersus,cunner,1,,Alive,
22,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Ovalipes ocellatus,lady crab,2,,Alive,
23,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Hemagrapsis sanguineus,asian shore crab,16,,"6 Alive, 10 dead",
24,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,Callinectes sapidus,blue crab,1,,Alive,
25,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,NaN,sponge,1,,Alive,
26,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,NaN,hydra medusa,4,,Alive,
27,6/14/2015,13:22,80 F,20 C,,,DO 4,7,33,,,50,"Cynthia, Isa, Shellita, Krista, Anita, Jeannely",,crangm septiaspinosa,sand shrimp,9,,Alive,
28,7/10/2015,10:45 AM,84F,26 C,,,DO 4,7,36,,,55,"Shellita,Isa,Nim, Maria,Adrianna,Hawa",,Paralichthys dentatus,Summer Flounder,1,,Alive,
29,7/10/2015,10:45 AM,84F,26 C,,,DO 4,7,36,,,55,"Shellita,Isa,Nim, Maria,Adrianna,Hawa",,Menidia menidia,Atlantic Silverside,23,,Alive,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Periwinkle,1,1,NaN,
101,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Atlantic Menhaden,6,0,NaN,
102,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Comb Jelly,17,0,NaN,
103,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Blue Crab,6,2,largest ~ 3 inches,
104,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Tautog,3,3,NaN,
105,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Long Clawed Hermit Crab,18,18,NaN,
106,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Ribbed Mussel,1,1,NaN,
107,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Pipefish,2,0,2.5 in,
108,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silverside,12,4,NaN,
109,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Bay Anchovy,4,0,3 dead,
110,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silver Perch,4,1,NaN,
111,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Blue Crab,3,0,NaN,
112,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Hermit Crab,10,10,NaN,
113,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Moon Jelly,1,0,NaN,
114,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Comb Jelly,17,0,NaN,
115,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Mud Snail,6,0,1 dead,
116,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Skilletfish,1,1,NaN,
117,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,shore shrimp,6,6,NaN,
118,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Sand Shrimp,4,4,NaN,
119,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Bluefish,11,0,1 dead,
120,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Atlantic Silverside,5,0,1 dead,
121,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Porgy,1,0,NaN,
122,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Comb Jelly,70,0,NaN,
123,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Moon Jelly,2,0,NaN,
124,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Mud Snail,2,0,NaN,
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [145]:
df_2014 =  pd.read_csv(csv_2014)

df_2014.rename(columns={"Weather (exact air temp):": 'Weather & Air Temp:', "#of Participants":'# of visitors (Public Seine ONLY)', "Instructors/Staff:":"Instructors/ Seine Staff:", "Other info (Dead/Alive)":"Other info (Gender, Length, Dead/Alive, other physical description)"}, inplace=True)
df_2014 = add_columns(df_2014, combined_df)

df_2014 = reformat_recent(df_2014)

combined_df = pd.concat([df_2014,combined_df], axis=0)

In [146]:
df_2013 =  pd.read_csv(csv_2013)
df_2013.columns = list(df_2013.loc[0])
df_2013 = df_2013[1:]

weatherAndTemp = []
for i,val in enumerate(list(df_2013['Weather:'])):
    temp_val = list(df_2013["Air Temp:"])[i]
    if temp_val == temp_val:
        weatherAndTemp.append(val + " " + temp_val)
    else:
        weatherAndTemp.append(val)


df_2013['Weather & Air Temp:'] =  weatherAndTemp

df_2013.rename(columns={ "Instructors":"Instructors/ Seine Staff:"}, inplace=True)
df_2013 = df_2013.reset_index()
df_2013 = add_columns(df_2013, combined_df)


df_2013 = reformat_recent(df_2013)
combined_df = pd.concat([df_2013,combined_df], axis=0)

In [147]:
combined_df

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
0,6/4/2013,NaN,NaN,,,,,,,,,,,,,Blueback herring,1,,,
1,6/4/2013,NaN,NaN,,,,,,,,,,,,,Bay anchovy,1,,,
2,6/4/2013,NaN,NaN,,,,,,,,,,,,,Summer flounder,1,,,
3,6/4/2013,NaN,NaN,,,,,,,,,,,,,glass shrimp,1,,,
4,6/4/2013,NaN,NaN,,,,,,,,,,,,,asian shore crab,1,,,
5,6/4/2013,NaN,NaN,,,,,,,,,,,,,comb jellies,15,,,
6,6/4/2013,NaN,NaN,,,,,,,,,,,,,golden star tunicate,1 clump,,,
7,6/4/2013,NaN,NaN,,,,,,,,,,,,,sea squirt/solitary tunicate,1,,,
8,6/17/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,American eel,1,,,
9,6/17/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,Atlantic Silverside,20,,,
10,6/17/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,Comb jellies,50,,,
11,6/17/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,Shrimp,1,,,
12,6/18/2013,NaN,NaN,,,,,,,,,,,,,bluefish (juvenile),30,,,
13,6/18/2013,NaN,NaN,,,,,,,,,,,,,comb jelly,15,,,
14,6/18/2013,NaN,NaN,,,,,,,,,,,,,true jelly,1,,,
15,6/21/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,American eel,2,,,
16,6/21/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,Comb jellies,20,,,
17,6/21/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,asian shore crab,2,,,
18,6/21/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,Hermit crab,1,,,
19,6/21/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,Snail,1,,,
20,6/21/2013,10 am - 1 pm,"Sunny, 80s",,,,,,,,,,,,,Shore shrimp,4,,,
21,6/22/2013,NaN,NaN,,,,,,,,,,,,,1 oyster toadfish (caught in traffic cone),1,,,
22,6/22/2013,NaN,NaN,,,,,,,,,,,,,1 black sea bass,1,,,
23,6/22/2013,NaN,NaN,,,,,,,,,,,,,20 ctenophores,20,,,
24,6/22/2013,NaN,NaN,,,,,,,,,,,,,1 oyster drill,1,,,
25,6/22/2013,NaN,NaN,,,,,,,,,,,,,5 Asian shore crabs,5,,,
26,7/18/2013,NaN,hot and sunny,,,,,,,,,,,,,comb jelly,15,,,
27,7/18/2013,NaN,hot and sunny,,,,,,,,,,,,,bluefish,7,,,
28,7/18/2013,NaN,hot and sunny,,,,,,,,,,,,,atlantic silverside,10,,,
29,7/19/2013,11:30 - 1:00,hot and clear,,,,,,,,,,,,,comb jelly,20,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Periwinkle,1,1,NaN,
101,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Atlantic Menhaden,6,0,NaN,
102,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Comb Jelly,17,0,NaN,
103,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Blue Crab,6,2,largest ~ 3 inches,
104,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Tautog,3,3,NaN,
105,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Long Clawed Hermit Crab,18,18,NaN,
106,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Ribbed Mussel,1,1,NaN,
107,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Pipefish,2,0,2.5 in,
108,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silverside,12,4,NaN,
109,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Bay Anchovy,4,0,3 dead,
110,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silver Perch,4,1,NaN,
111,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Blue Crab,3,0,NaN,
112,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Hermit Crab,10,10,NaN,
113,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Moon Jelly,1,0,NaN,
114,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Comb Jelly,17,0,NaN,
115,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Mud Snail,6,0,1 dead,
116,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Skilletfish,1,1,NaN,
117,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,shore shrimp,6,6,NaN,
118,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Sand Shrimp,4,4,NaN,
119,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Bluefish,11,0,1 dead,
120,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Atlantic Silverside,5,0,1 dead,
121,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Porgy,1,0,NaN,
122,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Comb Jelly,70,0,NaN,
123,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Moon Jelly,2,0,NaN,
124,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Mud Snail,2,0,NaN,
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [148]:
def reformat_2012():

    df_2012 = pd.read_csv(csv_2012)
    columns = df_2012.columns.values
    #Find columns with 2 // as with dates 03/30/15
    date_columns = [date for date in columns if date.count('/') == 2 ]
    df_list = []
    
    # for every date make a separate dataframe
    for date_col_name in date_columns:
        #get all species names and all values for that day
        abridged_df = df_2012[['Name of Species', date_col_name]].head(50)
        abridged_df['Date']  = date_col_name
        #remove all rows where nothing was caught
        abridged_df = abridged_df.dropna()
        abridged_df.rename(columns={date_col_name: 'Quantity', 'Name of Species': 'Common Name'}, inplace=True)
        df_list.append(abridged_df)
    #combine all the dataframes into one big one
    sein_df_2012 = pd.concat(df_list)
    return sein_df_2012

In [149]:
df_2012 = reformat_2012()

df_2012 = add_columns(df_2012, combined_df)
new_quantities = []
for val in list(df_2012['Quantity']):
    if type(val) == float:
        new_quantities.append(str(int(val)))
    else:
        new_quantities.append(val)
df_2012['Quantity'] = new_quantities

combined_df = pd.concat([df_2012,combined_df], axis=0)

In [150]:
combined_df.tail()

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [151]:
def reformat_2011():
    df_2011 = pd.read_csv(csv_2011)            
    #set proper column indexes and remove junk rows
    df_2011.columns = df_2011.iloc[1]
    df_2011.reindex(df_2011.index.drop(1))
    df_2011 = df_2011.drop([0,1,36])
    #renaming columns to substitute for blank values '######' with approximations
    df_2011.columns = ['Name of Species', '5/10/2011', '5/14/2011', '5/20/2011', '5/28/2011',
           'Total Number May', '6/11/2011', '6/14/2011', '6/26/2011',
           'Total Number June', '7/10/2011', '7/11/2011', '7/12/2011',
           '7/13/2011', 'Total Number July', '8/02/2011', '8/9/2011',
           '8/10/2011', 'Total Number August', '9/10/2011', '9/20/2011', '9/26/2011',
           'Total Number Sept', 'Total Number October']
    #remove columns that are just sums of past columns
    selected_columns = [col for col in df_2011 if "Total" not in col]
    df_2011 = df_2011[selected_columns]
    df_2011.head()
    df_list_2011 = []
    for col in df_2011.columns.values:
        if col == 'Name of Species':
            continue
        abridged_df = df_2011[['Name of Species', col]]
        abridged_df['Date'] = col#datetime.strptime(col, '%m/%d/%Y' )
        abridged_df = abridged_df.dropna()
        abridged_df.rename(columns={col: 'Quantity', 'Name of Species': 'Common Name'}, inplace=True)
        df_list_2011.append(abridged_df)

    sein_df_2011 = pd.concat(df_list_2011)
    return sein_df_2011

In [152]:
df_2011 = reformat_2011()

df_2011 = add_columns(df_2011, combined_df)

combined_df = pd.concat([df_2011,combined_df], axis=0)

C:\Program Files\Anaconda2\lib\site-packages\ipykernel\__main__.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [153]:
combined_df.tail()

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [154]:
def reformat_2010():
    df_2010 = pd.read_csv(csv_2010)
    df_2010 = df_2010.drop([0])
    curr_date = df_2010.loc[1]
    for i, date in df_2010.iterrows():
        if pd.isnull(df_2010.loc[i, 'Unnamed: 0']):
            df_2010.loc[i, 'Unnamed: 0'] = curr_date
        else:
            curr_date = df_2010.loc[i, 'Unnamed: 0']
    df_2010 = df_2010.drop([1])
    #rename columns
    df_2010.rename(columns={"Unnamed: 0": "Date", "Seining catch 2010": "Common Name", "Unnamed: 2":"Other info (Gender, Length, Dead/Alive, other physical description)"}, inplace=True)
    df_2010 = df_2010.dropna(subset=['Common Name'])
    return df_2010

In [155]:
df_2010 = reformat_2010()

df_2010 =  add_columns(df_2010, combined_df)

combined_df = pd.concat([df_2010,combined_df], axis=0)

In [156]:
combined_df.tail()

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [157]:
def reformat_2009(): 
    df_2009 = pd.read_csv(csv_2009)
    df_2009 = df_2009.drop([0,1,16])
    curr_date = df_2009.loc[2]

    for i, date in df_2009.iterrows():
        if pd.isnull(df_2009.loc[i, 'Unnamed: 0']):
            df_2009.loc[i, 'Unnamed: 0'] = curr_date
        else:
            curr_date = df_2009.loc[i, 'Unnamed: 0']

    df_2009 = df_2009[['Unnamed: 0', 'Seining catch 2009']]
    df_2009 = df_2009.dropna()
    #rename columns
    df_2009.rename(columns={"Unnamed: 0": "Date", "Seining catch 2009": "Common Name"}, inplace=True)
    #datetime_object = datetime.strptime('Jun 1 2005  1:33PM', '%b %d %Y %I:%M%p')
    return df_2009

In [158]:
df_2009 = reformat_2009()

df_2009 =  add_columns(df_2009, combined_df)

df_2009 = df_2009.drop([2])

combined_df = pd.concat([df_2009,combined_df], axis=0)

In [159]:
combined_df.tail()

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [160]:
def reformat_2008():
    df_2008 = pd.read_csv(csv_2008)
    df_2008 = df_2008.drop([0,1])
    curr_date = df_2008.loc[2]

    for i, date in df_2008.iterrows():
            if pd.isnull(df_2008.loc[i, 'Unnamed: 0']):
                df_2008.loc[i, 'Unnamed: 0'] = curr_date
            else:
                curr_date = df_2008.loc[i, 'Unnamed: 0']

    df_2008 = df_2008.drop([2])

    df_2008 = df_2008[['Unnamed: 0', 'Seining catch 2008']]
    df_2008 = df_2008.dropna()
    #rename columns
    df_2008.rename(columns={"Unnamed: 0": "Date", "Seining catch 2008": "Common Name"}, inplace=True)
    return df_2008

In [161]:
df_2008 =  reformat_2008()

In [162]:
df_2008 =  add_columns(df_2008, combined_df)
combined_df = pd.concat([df_2008,combined_df], axis=0)

In [163]:
combined_df.tail()

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2,0,NaN,

In [164]:
combined_df['Quantity'] = combined_df['Quantity'].astype(str)

In [165]:
combined_df

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
3,"Saturday, September 13, 2008",,,,,,,,,,,,,,,sea squirt,,,,
4,"Saturday, September 13, 2008",,,,,,,,,,,,,,,shore shrimp,,,,
5,"Saturday, September 13, 2008",,,,,,,,,,,,,,,mantis shrimp,,,,
6,"Saturday, September 13, 2008",,,,,,,,,,,,,,,sand shrimp,,,,
7,"Saturday, September 13, 2008",,,,,,,,,,,,,,,hermit crab,,,,
8,"Saturday, September 13, 2008",,,,,,,,,,,,,,,oyster toadfish,,,,
9,"Saturday, September 13, 2008",,,,,,,,,,,,,,,striped bass,,,,
10,"Saturday, September 13, 2008",,,,,,,,,,,,,,,northern kingfish,,,,
11,"Saturday, September 13, 2008",,,,,,,,,,,,,,,northern pipefish,,,,
12,"Saturday, September 13, 2008",,,,,,,,,,,,,,,striped searobin,,,,
13,"Saturday, September 13, 2008",,,,,,,,,,,,,,,Atlantic silverside,,,,
14,"Saturday, September 13, 2008",,,,,,,,,,,,,,,anchovy,,,,
15,"Saturday, September 13, 2008",,,,,,,,,,,,,,,blue crab,,,,
16,"Saturday, September 13, 2008",,,,,,,,,,,,,,,lady crab,,,,
17,"Saturday, September 13, 2008",,,,,,,,,,,,,,,winter flounder,,,,
18,"Saturday, September 13, 2008",,,,,,,,,,,,,,,comb jelly,,,,
19,"Saturday, September 13, 2008",,,,,,,,,,,,,,,lion's mane jellyfish,,,,
3,"Saturday, June 20, 2009",,,,,,,,,,,,,,,bay anchovy,,,,
4,"Saturday, June 20, 2009",,,,,,,,,,,,,,,northern pipefish,,,,
5,"Saturday, June 20, 2009",,,,,,,,,,,,,,,striped bass,,,,
6,"Saturday, June 20, 2009",,,,,,,,,,,,,,,shore shrimp,,,,
7,"Saturday, June 20, 2009",,,,,,,,,,,,,,,sand shrimp,,,,
8,"Saturday, June 20, 2009",,,,,,,,,,,,,,,sea squirts,,,,
9,"Saturday, June 20, 2009",,,,,,,,,,,,,,,blue crab,,,,
10,"Saturday, June 20, 2009",,,,,,,,,,,,,,,comb jelly,,,,
11,"Saturday, June 20, 2009",,,,,,,,,,,,,,,hydroids,,,,
12,"Saturday, June 20, 2009",,,,,,,,,,,,,,,"hermit crab,",,,,
13,"Saturday, June 20, 2009",,,,,,,,,,,,,,,snails,,,,
14,"Saturday, June 20, 2009",,,,,,,,,,,,,,,Two hemigrapsis molts were found on the beach.,,,,
18,"Wednesday, September 23, 2009",,,,,,,,,,,,,,,Lion's mane Jellyfish (Cyanea capillata),,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Periwinkle,1.0,1,NaN,
101,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Atlantic Menhaden,6.0,0,NaN,
102,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Comb Jelly,17.0,0,NaN,
103,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Blue Crab,6.0,2,largest ~ 3 inches,
104,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Tautog,3.0,3,NaN,
105,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Long Clawed Hermit Crab,18.0,18,NaN,
106,9/21/18,9:40 AM,72,74,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,,Ribbed Mussel,1.0,1,NaN,
107,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Pipefish,2.0,0,2.5 in,
108,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silverside,12.0,4,NaN,
109,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Bay Anchovy,4.0,0,3 dead,
110,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Silver Perch,4.0,1,NaN,
111,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Blue Crab,3.0,0,NaN,
112,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Hermit Crab,10.0,10,NaN,
113,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Moon Jelly,1.0,0,NaN,
114,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Comb Jelly,17.0,0,NaN,
115,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Mud Snail,6.0,0,1 dead,
116,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Skilletfish,1.0,1,NaN,
117,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,shore shrimp,6.0,6,NaN,
118,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",70,NaN,NaN,4,8,24,50,10,NaN,NaN,11,,Sand Shrimp,4.0,4,NaN,
119,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Bluefish,11.0,0,1 dead,
120,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Atlantic Silverside,5.0,0,1 dead,
121,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Porgy,1.0,0,NaN,
122,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Comb Jelly,70.0,0,NaN,
123,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Moon Jelly,2.0,0,NaN,
124,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Mud Snail,2.0,0,NaN,
125,10/6/18,9:30 AM -,"70, Cloudy",70,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,10,7,2,14,,Long Clawed Hermit Crab,5.0,0,NaN,
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Flounder,1.0,1,NaN,
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Striped Bass,8.0,5,NaN,
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Silverside,13.0,6,NaN,
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",60,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,,Herring,2.0,0,NaN,

In [168]:
#combined_df.apply(lambda x: x.str.strip()).replace('', np.nan).tail()

In [169]:
combined_df = combined_df.apply(lambda x: x.str.strip()).replace('', np.nan)

In [170]:
combined_df

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
3,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea squirt,NaN,NaN,NaN,NaN
4,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,shore shrimp,NaN,NaN,NaN,NaN
5,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mantis shrimp,NaN,NaN,NaN,NaN
6,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sand shrimp,NaN,NaN,NaN,NaN
7,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hermit crab,NaN,NaN,NaN,NaN
8,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,oyster toadfish,NaN,NaN,NaN,NaN
9,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,striped bass,NaN,NaN,NaN,NaN
10,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,northern kingfish,NaN,NaN,NaN,NaN
11,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,northern pipefish,NaN,NaN,NaN,NaN
12,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,striped searobin,NaN,NaN,NaN,NaN
13,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Atlantic silverside,NaN,NaN,NaN,NaN
14,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,anchovy,NaN,NaN,NaN,NaN
15,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,blue crab,NaN,NaN,NaN,NaN
16,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lady crab,NaN,NaN,NaN,NaN
17,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,winter flounder,NaN,NaN,NaN,NaN
18,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,comb jelly,NaN,NaN,NaN,NaN
19,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lion's mane jellyfish,NaN,NaN,NaN,NaN
3,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bay anchovy,NaN,NaN,NaN,NaN
4,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,northern pipefish,NaN,NaN,NaN,NaN
5,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,striped bass,NaN,NaN,NaN,NaN
6,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,shore shrimp,NaN,NaN,NaN,NaN
7,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sand shrimp,NaN,NaN,NaN,NaN
8,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea squirts,NaN,NaN,NaN,NaN
9,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,blue crab,NaN,NaN,NaN,NaN
10,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,comb jelly,NaN,NaN,NaN,NaN
11,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hydroids,NaN,NaN,NaN,NaN
12,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"hermit crab,",NaN,NaN,NaN,NaN
13,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,snails,NaN,NaN,NaN,NaN
14,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Two hemigrapsis molts were found on the beach.,NaN,NaN,NaN,NaN
18,"Wednesday, September 23, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lion's mane Jellyfish (Cyanea capillata),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Periwinkle,1.0,1,NaN,NaN
101,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Atlantic Menhaden,6.0,0,NaN,NaN
102,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Comb Jelly,17.0,0,NaN,NaN
103,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Blue Crab,6.0,2,largest ~ 3 inches,NaN
104,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Tautog,3.0,3,NaN,NaN
105,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Long Clawed Hermit Crab,18.0,18,NaN,NaN
106,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Ribbed Mussel,1.0,1,NaN,NaN
107,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Pipefish,2.0,0,2.5 in,NaN
108,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Silverside,12.0,4,NaN,NaN
109,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Bay Anchovy,4.0,0,3 dead,NaN
110,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Silver Perch,4.0,1,NaN,NaN
111,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Blue Crab,3.0,0,NaN,NaN
112,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Hermit Crab,10.0,10,NaN,NaN
113,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Moon Jelly,1.0,0,NaN,NaN
114,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Comb Jelly,17.0,0,NaN,NaN
115,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Mud Snail,6.0,0,1 dead,NaN
116,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Skilletfish,1.0,1,NaN,NaN
117,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,shore shrimp,6.0,6,NaN,NaN
118,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Sand Shrimp,4.0,4,NaN,NaN
119,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Bluefish,11.0,0,1 dead,NaN
120,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Atlantic Silverside,5.0,0,1 dead,NaN
121,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Porgy,1.0,0,NaN,NaN
122,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Comb Jelly,70.0,0,NaN,NaN
123,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Moon Jelly,2.0,0,NaN,NaN
124,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Mud Snail,2.0,0,NaN,NaN
125,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Long Clawed Hermit Crab,5.0,0,NaN,NaN
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",NaN,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,NaN,Flounder,1.0,1,NaN,NaN
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",NaN,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,NaN,Striped Bass,8.0,5,NaN,NaN
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",NaN,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,NaN,Silverside,13.0,6,NaN,NaN
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",NaN,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,NaN,Herring,2.0,0,NaN,NaN

In [171]:
#combined_df[combined_df['Date'] =="4/25/2012"]

In [172]:
#combined_df.tail()

In [173]:
combined_df = combined_df.dropna(subset = ["Common Name"])

In [174]:
#combined_df.to_csv('deleteme.csv')

In [175]:
combined_df

,Date,Time,Weather & Air Temp:,Water Temp:,Tide Times,Tide is moving,DO,pH,Salinity,Turbidity,# student seiners (CLASSES ONLY),# of visitors (Public Seine ONLY),Instructors/ Seine Staff:,# Hauls,Scientific Name,Common Name,Quantity,# Brought to Ed Center,"Other info (Gender, Length, Dead/Alive, other physical description)",NOTES FROM SEINEING SEASON:
3,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea squirt,NaN,NaN,NaN,NaN
4,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,shore shrimp,NaN,NaN,NaN,NaN
5,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mantis shrimp,NaN,NaN,NaN,NaN
6,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sand shrimp,NaN,NaN,NaN,NaN
7,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hermit crab,NaN,NaN,NaN,NaN
8,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,oyster toadfish,NaN,NaN,NaN,NaN
9,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,striped bass,NaN,NaN,NaN,NaN
10,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,northern kingfish,NaN,NaN,NaN,NaN
11,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,northern pipefish,NaN,NaN,NaN,NaN
12,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,striped searobin,NaN,NaN,NaN,NaN
13,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Atlantic silverside,NaN,NaN,NaN,NaN
14,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,anchovy,NaN,NaN,NaN,NaN
15,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,blue crab,NaN,NaN,NaN,NaN
16,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lady crab,NaN,NaN,NaN,NaN
17,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,winter flounder,NaN,NaN,NaN,NaN
18,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,comb jelly,NaN,NaN,NaN,NaN
19,"Saturday, September 13, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lion's mane jellyfish,NaN,NaN,NaN,NaN
3,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bay anchovy,NaN,NaN,NaN,NaN
4,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,northern pipefish,NaN,NaN,NaN,NaN
5,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,striped bass,NaN,NaN,NaN,NaN
6,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,shore shrimp,NaN,NaN,NaN,NaN
7,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sand shrimp,NaN,NaN,NaN,NaN
8,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea squirts,NaN,NaN,NaN,NaN
9,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,blue crab,NaN,NaN,NaN,NaN
10,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,comb jelly,NaN,NaN,NaN,NaN
11,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hydroids,NaN,NaN,NaN,NaN
12,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"hermit crab,",NaN,NaN,NaN,NaN
13,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,snails,NaN,NaN,NaN,NaN
14,"Saturday, June 20, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Two hemigrapsis molts were found on the beach.,NaN,NaN,NaN,NaN
18,"Wednesday, September 23, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lion's mane Jellyfish (Cyanea capillata),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Periwinkle,1.0,1,NaN,NaN
101,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Atlantic Menhaden,6.0,0,NaN,NaN
102,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Comb Jelly,17.0,0,NaN,NaN
103,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Blue Crab,6.0,2,largest ~ 3 inches,NaN
104,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Tautog,3.0,3,NaN,NaN
105,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Long Clawed Hermit Crab,18.0,18,NaN,NaN
106,9/21/18,9:40 AM,72,NaN,NaN,OUT,4,8.1,18,45,NaN,NaN,"Kathy, Laura,Isa, City Growers Staff, CT, HM, SH",18,NaN,Ribbed Mussel,1.0,1,NaN,NaN
107,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Pipefish,2.0,0,2.5 in,NaN
108,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Silverside,12.0,4,NaN,NaN
109,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Bay Anchovy,4.0,0,3 dead,NaN
110,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Silver Perch,4.0,1,NaN,NaN
111,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Blue Crab,3.0,0,NaN,NaN
112,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Hermit Crab,10.0,10,NaN,NaN
113,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Moon Jelly,1.0,0,NaN,NaN
114,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Comb Jelly,17.0,0,NaN,NaN
115,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Mud Snail,6.0,0,1 dead,NaN
116,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Skilletfish,1.0,1,NaN,NaN
117,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,shore shrimp,6.0,6,NaN,NaN
118,10/5/18,11:30 AM - 12:10 PM,"67, Sunny",NaN,NaN,NaN,4,8,24,50,NaN,NaN,NaN,11,NaN,Sand Shrimp,4.0,4,NaN,NaN
119,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Bluefish,11.0,0,1 dead,NaN
120,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Atlantic Silverside,5.0,0,1 dead,NaN
121,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Porgy,1.0,0,NaN,NaN
122,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Comb Jelly,70.0,0,NaN,NaN
123,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Moon Jelly,2.0,0,NaN,NaN
124,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Mud Snail,2.0,0,NaN,NaN
125,10/6/18,9:30 AM -,"70, Cloudy",NaN,12:55 pm - 1:55 pm,OUT,4.5,5.5,16,27,NaN,7,2,14,NaN,Long Clawed Hermit Crab,5.0,0,NaN,NaN
126,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",NaN,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,NaN,Flounder,1.0,1,NaN,NaN
127,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",NaN,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,NaN,Striped Bass,8.0,5,NaN,NaN
128,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",NaN,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,NaN,Silverside,13.0,6,NaN,NaN
129,10/18/18,4:20 PM - 5:20 PM,"53, windy and sunny",NaN,5:14 PM - 10:38 AM,IN,6,8.49,14,NaN,NaN,St. Francis After-School,Christina,7,NaN,Herring,2.0,0,NaN,NaN

In [176]:
combined_df.to_csv('../Created CSVs/all_seins_all_data_reformatted.csv')