In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
#google sheets datasets
csv_2008 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=737788186&format=csv'
csv_2009 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1188626592&format=csv'
csv_2010 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1492092969&format=csv'
csv_2011 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1154911519&format=csv'
csv_2012 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1815364461&format=csv'
csv_2013 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1417342758&format=csv'
csv_2014 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1605738199&format=csv'
csv_2015 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=0&format=csv'
csv_2016 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=1068275557&format=csv'
csv_2017 = 'https://docs.google.com/spreadsheets/d/1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g/export?gid=126889157&format=csv'

In [4]:
df_2008 =  pd.read_csv(csv_2013)
sheet = '1TH5vctylelJl_yHXJtiAnW48R4dEI-t_E-ObkWZ6-5g'
df_2012 = pd.read_csv('https://docs.google.com/spreadsheets/d/' + 
                   sheet +
                   '/export?gid=1815364461&format=csv'
                  )
df_2008.head(20)

,Brooklyn Bridge Park Conservancy Seining Catch list 2013,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Date,Time,Weather:,Air Temp:,Instructors:,Common Name,Quantity
1,6/4/2013,NaN,NaN,NaN,NaN,Blueback herring,1
2,NaN,NaN,NaN,NaN,NaN,Bay anchovy,1
3,NaN,NaN,NaN,NaN,NaN,Summer flounder,1
4,NaN,NaN,NaN,NaN,NaN,glass shrimp,1
5,NaN,NaN,NaN,NaN,NaN,asian shore crab,1
6,NaN,NaN,NaN,NaN,NaN,comb jellies,15
7,NaN,NaN,NaN,NaN,NaN,golden star tunicate,1 clump
8,NaN,NaN,NaN,NaN,NaN,sea squirt/solitary tunicate,1
9,6/17/2013,10 am - 1 pm,"Sunny, 80s",NaN,"Nim, Eliza Connor",American eel,1
10,NaN,NaN,NaN,NaN,NaN,Atlantic Silverside,20
11,NaN,NaN,NaN,NaN,NaN,Comb jellies,50
12,NaN,NaN,NaN,NaN,NaN,Shrimp,1
13,6/18/2013,NaN,NaN,NaN,NaN,bluefish (juvenile),30
14,NaN,NaN,NaN,NaN,NaN,comb jelly,15
15,NaN,NaN,NaN,NaN,NaN,true jelly,1
16,6/21/2013,10 am - 1 pm,"Sunny, 80s",NaN,"Cynthia, Eliza, Sara, Natalia",American eel,2
17,NaN,NaN,NaN,NaN,NaN,Comb jellies,20
18,NaN,NaN,NaN,NaN,NaN,asian shore crab,2
19,NaN,NaN,NaN,NaN,NaN,Hermit crab,1